title: Quantitative Finance Book
author: Patrik Liba
copyright: "2025"
logo: logo.jpeg

execute:
  execute_notebooks: cache
  allow_errors: true
  timeout: 300

latex:
  latex_documents:
    targetname: QFB.tex

bibtex_bibfiles:
  - references.bib

repository:
  url: https://github.com/libapatrik/QFB
  branch: master

html:
  use_issues_button: true
  use_repository_button: true

parse:
  myst_enable_extensions:
    - dollarmath
    - amsmath