# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Quantitative Finance Book
author: Patrik Liba
copyright: "2025"
logo: logo.jpeg

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force
  timeout: 300 # for fully repr table in LSMC

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: QFB.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/libapatrik/Quantitative-Finance-Book # Online location of your book
  path_to_book: QFB  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

# bibtex_bibfiles:
#   - references.bib

# Sphinx extensions for advanced features
sphinx:
  extra_extensions:
    - sphinx_copybutton
    - sphinx_togglebutton
    - sphinx.ext.intersphinx
  config:
    html_theme_options:
      repository_url: https://github.com/libapatrik/Quantitative-Finance-Book
      use_repository_button: true
      use_issues_button: true
      use_download_button: true
      use_fullscreen_button: true
parse:
  myst_enable_extensions:
    - dollarmath
    - amsmath